# Generated by Django 3.1.7 on 2023-11-28 13:59

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('comuna', models.CharField(max_length=200, verbose_name='Comuna')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(upload_to='cards/')),
                ('fecha', models.DateField()),
                ('cupos', models.IntegerField()),
                ('inscritos', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del club')),
                ('abreviado', models.CharField(max_length=10, verbose_name='Nombre abreviado')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('correo', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo electronico')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CuotaAnual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('año', models.PositiveIntegerField(verbose_name='Año cuotas')),
                ('monto_cuota', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CuotaAnual',
                'verbose_name_plural': 'CuotasAnuales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='front/')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, max_length=254, upload_to='front/files/')),
            ],
            options={
                'verbose_name': 'Front',
                'verbose_name_plural': 'Fronts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='galeria/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('parrafo', models.TextField()),
                ('img', models.ImageField(upload_to='links/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NormaRegla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del perfil')),
                ('archivo', models.FileField(upload_to='normas_reglas/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Norma_Regla',
                'verbose_name_plural': 'Normas_Reglas',
                'ordering': ['titulo', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='noticias/')),
                ('fecha', models.DateField()),
                ('resumen', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('is_aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('is_pendiente', models.BooleanField(default=True, verbose_name='Pendiente')),
                ('img1', models.ImageField(blank=True, upload_to='noticias/')),
                ('img2', models.ImageField(blank=True, upload_to='noticias/')),
                ('img3', models.ImageField(blank=True, upload_to='noticias/')),
                ('img4', models.ImageField(blank=True, upload_to='noticias/')),
                ('img5', models.ImageField(blank=True, upload_to='noticias/')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(choices=[('I', 'Región de Tarapacá  '), ('II', 'Región de Antofagasta  '), ('III', 'Región de Atacama  '), ('IV', 'Región de Coquimbo  '), ('V', 'Región de Valparaíso    '), ('VI', 'Región del Libertador General Bernardo O’Higgins    '), ('VII', 'Región del Maule    '), ('VIII', 'Región del Bio-bío  '), ('IX', 'Región de La Araucanía  '), ('X', 'Región de Los Lagos '), ('XI', 'Región Aysén del General Carlos Ibáñez del Campo '), ('XII', 'Región de Magallanes y Antártica Chilena   '), ('XIII', 'Región Metropolitana de Santiago    '), ('XIV', 'Región de Los Ríos '), ('XV', 'Región de Arica y Parinacota   '), ('XVI', 'Región de Ñuble ')], default='XIII', max_length=50, verbose_name='Region')),
                ('comentario', models.TextField(default='Sin comentario')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo')),
                ('descripcion', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('region', models.CharField(choices=[('I', 'Región de Tarapacá  '), ('II', 'Región de Antofagasta  '), ('III', 'Región de Atacama  '), ('IV', 'Región de Coquimbo  '), ('V', 'Región de Valparaíso    '), ('VI', 'Región del Libertador General Bernardo O’Higgins    '), ('VII', 'Región del Maule    '), ('VIII', 'Región del Bio-bío  '), ('IX', 'Región de La Araucanía  '), ('X', 'Región de Los Lagos '), ('XI', 'Región Aysén del General Carlos Ibáñez del Campo '), ('XII', 'Región de Magallanes y Antártica Chilena   '), ('XIII', 'Región Metropolitana de Santiago    '), ('XIV', 'Región de Los Ríos '), ('XV', 'Región de Arica y Parinacota   '), ('XVI', 'Región de Ñuble ')], default='XIII', max_length=50, verbose_name='Region')),
                ('descripcion', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='torneo/')),
                ('fecha', models.DateField()),
                ('cupos', models.IntegerField()),
                ('inscritos', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('proximo', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-proximo', 'activo', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='listado/')),
                ('order', models.IntegerField(default=0)),
                ('actual', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Listado',
                'verbose_name_plural': 'Listados',
                'ordering': ['tipo', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('monto_descuento', models.PositiveIntegerField(blank=True, null=True)),
                ('monto_cargo', models.PositiveIntegerField(blank=True, null=True)),
                ('monto_pago', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado_pago', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Estado de la cuota')),
                ('order', models.IntegerField(default=0)),
                ('año', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.cuotaanual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='socio club')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del campeonato')),
                ('fecha', models.DateField(verbose_name='Fecha de torneo')),
                ('bases', models.FileField(upload_to='bases/')),
                ('order', models.IntegerField(default=0)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.club', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['order'],
            },
        ),
    ]
